GET http://localhost:8000/chats

###

POST http://localhost:8000/chats
Content-Type: application/json

{
  "user": "How's the weather today?"
}

###
//Should throw an error
POST http://localhost:8000/chats
Content-Type: application/json

{
  "user1": "How's the weather today?"
}

###
// Delete chats and re-initialise with forst greeting message
// Not to be used in the react app
DELETE http://localhost:8000/chats